[project]
name = "naive-bayes-detector-spam"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "fastapi[standard]>=0.103.2",
    "nltk>=3.8.1",
    "pandas>=1.1.5",
    "uvicorn>=0.22.0",
]
